name: "Greet PR Creator"

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write
  issues: write

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet Contributor
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prAuthor = context.payload.pull_request.user.login;
            const prNumber = context.payload.pull_request.number;

            const greetings = [
              `ЁЯОЙ рдзрдиреНрдпрд╡рд╛рдж @${prAuthor} рдЬреА! рдЖрдкрдХрд╛ рдпреЛрдЧрджрд╛рди рд╣рдорд╛рд░реЗ рдкреНрд░реЛрдЬреЗрдХреНрдЯ рдХреЗ рд▓рд┐рдП рдмрд╣реБрдд рдорд╣рддреНрд╡рдкреВрд░реНрдг рд╣реИред ЁЯЩМ`,
              `ЁЯЪА рдХреГрдкрдпрд╛ рдЕрдкрдиреЗ рдпреЛрдЧрджрд╛рди рдХреЛ [Discord](https://discord.gg/cYkT2F3v) рдкрд░ рд╕рд╛рдЭрд╛ рдХрд░реЗрдВ рддрд╛рдХрд┐ рд╣рдо рдЗрд╕реЗ рдФрд░ рднреА рдмреЗрд╣рддрд░ рдмрдирд╛ рд╕рдХреЗрдВред\nрдХреГрдкрдпрд╛ рдЕрдЧрд▓реА рдмрд╛рд░ рдпреЛрдЧрджрд╛рди рджреЗрдиреЗ рд╕реЗ рдкрд╣рд▓реЗ рдЕрдкрдиреА Local Repository рдХреЛ рдЕрдкрдбреЗрдЯ (fetch/pull) рдХрд░рдирд╛ рди рднреВрд▓реЗрдВ рддрд╛рдХрд┐ рдХреЛрдИ conflict рди рд╣реЛред ЁЯШК`
            ];

            for (const msg of greetings) {
              try {
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: prNumber,
                  body: msg
                });
                console.log("тЬЕ Comment posted:", msg);
              } catch (err) {
                if (err.status === 403) {
                  console.warn("тЪая╕П Cannot post comment тАФ resource not accessible. Probably needs workflow approval for forked PR.");
                } else {
                  throw err;
                }
              }
            }
